version: "3.7"

services:
  db:
    image: mysql
    restart: always
    container_name: mysql-test-brian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-brian
    ports:
      - 3306:3306

  portal:
    image: presentacion:1.0.0
    container_name: portal
    ports:
      - 82:80

  logica:
    build: ./
    restart: always
    container_name: logica
    #script: alembic upgrade head
    ports:
      - 8002:8000
    links:
      - db
