FROM node:19.0.1-alpine as build

WORKDIR /app

copy . .

RUN npm install
RUN npm run build

FROM nginx:1.17.1-alpine
COPY --from=build /app/dist/presentacion /usr/share/nginx/html
COPY /server/nginx.conf /etc/nginx/config.d/default.conf
EXPOSE 80
